version: 2.1

orbs:
  github-cli: circleci/github-cli@2.7

parameters:
  rollback_tag:
    type: string
    default: ""

jobs:
  deploy:
    docker:
      - image: cimg/base:current
    steps:
      - checkout

      - run:
          name: Login GitHub App
          command: |
            echo "$GH_APP_PRIVATE_KEY" | base64 --decode > private-key.pem
            INSTALLATION_TOKEN=$(./.circleci/scripts/authorize-github-app-token.sh \
              "$GH_APP_ID" \
              "$GH_APP_INSTALLATION_ID" \
              "private-key.pem"
            )
            echo "export GITHUB_TOKEN=$INSTALLATION_TOKEN" >> $BASH_ENV

      - github-cli/setup

      - run:
          name: Set deployment name
          command: |
            PR_JSON=$(gh api "repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/commits/${CIRCLE_SHA1}/pulls" \
               --jq '.[] | select(.base.ref == "master") | {number, url: .html_url}'
            )

            echo $PR_JSON

            PR_NUMBER=$(echo $PR_JSON | jq -r '.number')
            PR_URL=$(echo $PR_JSON | jq -r '.url')

            echo "export VERSION=production-$(date +%Y.%m.%d)-${PR_NUMBER}" >> $BASH_ENV
            echo "export PR_URL=${PR_URL}" >> $BASH_ENV

      - run:
          name: Do something
          command: echo $CIRCLE_SHA1

      - run:
          name: Create GitHub tag
          command: |
            git config user.email "ci@example.com"
            git config user.name "CircleCI"
            git tag -a "$VERSION" -m "${CIRCLE_BUILD_URL}"
            git push origin "$VERSION"

      - run:
          name: Create GitHub release
          command: |
            gh release create "${VERSION}" \
              --verify-tag \
              --title "${VERSION}" \
              --generate-notes

  rollback:
    docker:
      - image: cimg/base:current
    steps:
      - checkout

      - run:
          name: Get rollback sha
          command: |
            ROLLBACK_SHA=$(git rev-parse "<< pipeline.parameters.rollback_tag >>^{commit}")
            echo "export ROLLBACK_SHA=${ROLLBACK_SHA}" >> $BASH_ENV

      - run:
          name: Checkout target
          command: |
            git checkout "${ROLLBACK_SHA}"
            git rev-parse HEAD

      - run:
          name: Login GitHub App
          command: |
            echo "$GH_APP_PRIVATE_KEY" | base64 --decode > private-key.pem
            INSTALLATION_TOKEN=$(./.circleci/scripts/authorize-github-app-token.sh \
              "$GH_APP_ID" \
              "$GH_APP_INSTALLATION_ID" \
              "private-key.pem"
            )
            echo "export GITHUB_TOKEN=$INSTALLATION_TOKEN" >> $BASH_ENV

      - github-cli/setup

      - run:
          name: Replace latest GitHub release
          command: |
            LATEST_RELEASE=$(gh release view --json body,tagName)
            LATEST_RELEASE_TAG=$(echo "$LATEST_RELEASE" | jq -r '.tagName')
            LATEST_RELEASE_BODY=$(echo "$LATEST_RELEASE" | jq -r '.body')

            LATEST_RELEASE_BODY_REPLACED=$(cat \<<-EOF
            ## 🚨 Rollbacked

            - **Target version**: << pipeline.parameters.rollback_tag >>
            - **Rollbacked by**: ${CIRCLE_USERNAME}

            ---

            ${LATEST_RELEASE_BODY}
            EOF
            )

            gh release edit "$LATEST_RELEASE_TAG" \
              --title "[ROLLBACKED] ${LATEST_RELEASE_TAG}" \
              --notes "${LATEST_RELEASE_BODY_REPLACED}"

            gh release edit "<< pipeline.parameters.rollback_tag >>" --latest

workflows:
  rollback-workflow:
    when:
      not:
        equal: ["", << pipeline.parameters.rollback_tag >>]
    jobs:
      - rollback:
          filters:
            branches:
              only:
                - master

  deploy-workflow:
    when:
      equal: ["", << pipeline.parameters.rollback_tag >>]
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
