version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/base:current
    steps:
      - checkout

      - run:
          name: Do something
          command: echo Hello, World!

      - run:
          name: Create GitHub tag
          command: |
            git config user.email "ci@example.com"
            git config user.name "CircleCI"
            git tag -a "$VERSION" -m "CI: ${CIRCLE_BUILD_URL}\nTriggerd by: ${CIRCLE_USERNAME}"
            git push origin "$VERSION"

workflows:
  deploy-workflow:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
