version: 2.1

orbs:
  github-cli: circleci/github-cli@2.7

jobs:
  deploy:
    docker:
      - image: cimg/base:current
    steps:
      - checkout

      - run:
          name: Login GitHub App
          command: |
            echo "$GH_APP_PRIVATE_KEY" | base64 --decode > private-key.pem
            INSTALLATION_TOKEN=$(./.circleci/scripts/authorize-github-app-token.sh \
              "$GH_APP_ID" \
              "$GH_APP_INSTALLATION_ID" \
              "private-key.pem"
            )
            echo "export GITHUB_TOKEN=$INSTALLATION_TOKEN" >> $BASH_ENV

      - github-cli/setup

      - run:
          name: Set deployment name
          command: |
            echo "repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/commits/${CIRCLE_SHA1}/pulls"

            PR_JSON=$(gh api "repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/commits/${CIRCLE_SHA1}/pulls" \
               --jq '.[] | select(.base.ref == "master") | {number, url: .html_url}'
            )

            echo $PR_JSON

            PR_NUMBER=$(echo $PR_JSON | jq -r '.number')
            PR_URL=$(echo $PR_JSON | jq -r '.url')

            echo "export VERSION=production-$(date +%Y.%m.%d)-${PR_NUMBER}" >> $BASH_ENV
            echo "export PR_URL=${PR_URL}" >> $BASH_ENV

      - run:
          name: Do something
          command: echo $CIRCLE_SHA1

      - run:
          name: Create GitHub tag
          command: |
            git config user.email "ci@example.com"
            git config user.name "CircleCI"
            git tag -a "$VERSION" -m "CI: ${CIRCLE_BUILD_URL}\nTriggerd by: ${CIRCLE_USERNAME}\nPR:${PR_URL}"
            git push origin "$VERSION"

      - run:
          name: Create GitHub release
          command: |
            gh release create "${VERSION}" \
              --verify-tag \
              --title "${VERSION}" \
              --generate-notes

workflows:
  deploy-workflow:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
