version: 2.1

jobs:
  rollback:
    docker:
      - image: cimg/base:current
    steps:
      - checkout

      - run:
          name: Do something
          command: echo $CIRCLE_SHA1

workflows:
  rollback-workflow:
    jobs:
      - rollback:
